version: '3.8'

services:
  mongo-db:
    image: mongo:8.0.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - mongo:/data/db
    ports:
      - 27019:27017

volumes:
  mongo:
    external: false